### ISSUE TITLE
Allow comment and description fields to remain empty

### ISSUE THREAD

**Issue by tibonihoo** [tibonihoo/wateronmars#18]
Requires a database scheme update

**Comment by pillsbury7901** [comment]
Hello, I thought I might try to fix this bug. How can I reproduce the error?

**Comment by tibonihoo** [comment]
Err... wow a first contributor... great!

To reproduce the error, you have to do it manually: run the server and add a bookmark. It's an annoying flaw of wateronmars' unit tests that they can't reproduce the problem (a contribution just for such a test would be very much welcome btw :))

Also I've got a precise idea on the solution for this one: it requires to change some models' fields to make them have the option blank=true. But the changes on the models of wateronmars are tracked via the django-south migration library.

All in all it's probably a matter of <10 lines of code and 5 command line actions but it requires some learning of various components.

Since I don't know experimented you are with all that let me give a few starting tips:
- once you have the source of wateronmars, install the requirements with pip requirements-dev.txt (you may consider doing so in a virtualenv but that's not compulsory)
- run 'fab db_reset'
- to serve a local instance of wateronmars, run 'fab serve'
- then comes a trick: in wateronmars/settings.py you should then set DEMO to False, in order to be able to reproduce the bug. But this must be done after having run the local server once !
- you can then 'fab serve' again and try to reproduce the bug manually
- after you've done the fixes, you should register the change of the db as migration and consider reading more about south at http://south.aeracode.org/
- then 'fab db_update' will actually update the db so you can check if the fix is effdctive.

Feel free to ask for more info, considering the lack of general doc for wateronmars even the first most basic questions you will have are a great help to build such a doc !

**Comment by nickzuck** [comment]
Hi there ! I am interested in fixing this bug ...... I have the read the instructions above and will start working on it

**Comment by achyutjoshi** [comment]
Hey! I am new to the whole open source world. I will try to get this fixed.

**Comment by achyutjoshi** [comment]
Sorry, but is it necessary to have linux? can i work with windows?

**Comment by nickzuck** [comment]
Yes you can work with windows ..You just need to install 'make' and 'cygwin terminal' ....That will do

**Comment by pillsbury7901** [comment]
Okay, I made the blank=true option available to the various description and comment fields. I hope this finds you well. Please let me know if the errors have been corrected.

**Comment by tibonihoo** [comment]
Hello,

I answered on the pull request, but thanks again for contributing to  wateronmars. I think you should try to generate a migration file with south (see link in original bug description). But feel free to tell me if I'm mistaken and that no migration should be generated for this change.

Also please note that I will have almost no connection to internet for almost 2 weeks, so I may not be able to answer question quickly in this laps of time.

**Comment by rkgudboy** [comment]
Has the Comment and Description bug been fixed ?
Any other current issue on which I can work ?

**Comment by tibonihoo** [comment]
@rkgudboy Sorry for the late reply (internet connection issue). The bug here is probably very close to be fixed indeed.

If you're still willing to work on another task the following one may be interesting: #17 where another user asked a question some time ago. If he is still interested maybe you can try to work jointly with him (since wateronmars doesn't come yet with a good developer's guide, this may be helpful and interesting to work in group even on small features).
